version: '3'
services:
  db-test:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=server_dev
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
  web-test:
    image: starefossen/ruby-node
    command: bash -c "cd /app && bundle install && rake db:migrate && rails s"
    volumes:
      - /home/xero/jenkins/jenkins_home/workspace/project-open-source:/app   # Workspace
      - /home/cache/bundle:/usr/local/bundle                              # Cache gemfiles
      - /home/cache/node_modules:/app/node_modules                        # Cache yarn files
      - /home/xero/.ssh:/root/.ssh                                       # SSH keys (for git)
    ports:
      - "3000:3000"
    depends_on:
      - db-test


# version: "3.9"
# services:
#   db:
#     image: postgres
#     volumes:
#       - ./tmp/db:/var/lib/postgresql/data
#     environment:
#       POSTGRES_PASSWORD: password
#   web:
#     build: .
#     command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
#     volumes:
#       - .:/myapp
#     ports:
#       - "3000:3000"
#     depends_on:
#       - db
